// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v5.26.1
// source: classService/v1/classService.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationClassServiceAddClass = "/classService.v1.ClassService/AddClass"
const OperationClassServiceSearchClass = "/classService.v1.ClassService/SearchClass"

type ClassServiceHTTPServer interface {
	AddClass(context.Context, *AddClassRequest) (*AddClassReply, error)
	// SearchClass Sends a greeting
	SearchClass(context.Context, *SearchRequest) (*SearchReply, error)
}

func RegisterClassServiceHTTPServer(s *http.Server, srv ClassServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/classService/search/{searchKeyWords}", _ClassService_SearchClass0_HTTP_Handler(srv))
	r.POST("/classService/addByHand", _ClassService_AddClass0_HTTP_Handler(srv))
}

func _ClassService_SearchClass0_HTTP_Handler(srv ClassServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClassServiceSearchClass)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchClass(ctx, req.(*SearchRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchReply)
		return ctx.Result(200, reply)
	}
}

func _ClassService_AddClass0_HTTP_Handler(srv ClassServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddClassRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationClassServiceAddClass)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddClass(ctx, req.(*AddClassRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddClassReply)
		return ctx.Result(200, reply)
	}
}

type ClassServiceHTTPClient interface {
	AddClass(ctx context.Context, req *AddClassRequest, opts ...http.CallOption) (rsp *AddClassReply, err error)
	SearchClass(ctx context.Context, req *SearchRequest, opts ...http.CallOption) (rsp *SearchReply, err error)
}

type ClassServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewClassServiceHTTPClient(client *http.Client) ClassServiceHTTPClient {
	return &ClassServiceHTTPClientImpl{client}
}

func (c *ClassServiceHTTPClientImpl) AddClass(ctx context.Context, in *AddClassRequest, opts ...http.CallOption) (*AddClassReply, error) {
	var out AddClassReply
	pattern := "/classService/addByHand"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationClassServiceAddClass))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ClassServiceHTTPClientImpl) SearchClass(ctx context.Context, in *SearchRequest, opts ...http.CallOption) (*SearchReply, error) {
	var out SearchReply
	pattern := "/classService/search/{searchKeyWords}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationClassServiceSearchClass))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
