server:
  http:
    addr: 0.0.0.0:18000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:19000
    timeout: 10s
data:
  es:
    url: "http://127.0.0.1:9200"
    setsniff: false
    username: "elastic"
    password: "12345678"
registry:
  etcd:
    addr: "127.0.0.1:2379"
    username: root
    password: "muxistudio304"