server:
  http:
    addr: 0.0.0.0:8900
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9900
    timeout: 1s
data:
  es:
    url: "http://127.0.0.1:9200"
    setsniff: false
registry:
  etcd:
    addr: "127.0.0.1:2379"